### PR TITLE
French - fr translation

### PR DESCRIPTION
**Pull request by cyrez**
French translation :)

### CODE REVIEW

**Comment by ImLunaHey** [comment]
@cyrezdev thank you. 🙏 

we're about to start adding regions. would this be french french or another dialect of french like canadian french?

**Comment by cyrezdev** [comment]
@ImLunaHey for region, it's fr-FR

For Canadians (fr-CA), there may be a difference (we are cousins ​​​​but do not always use the same word depending on the context)

For Belgians (fr-BE) it would be the same.

**Comment by ImLunaHey** [comment]
@cyrezdev gotcha. did you want to set this as `fr-FR` then? see https://github.com/ImLunaHey/bsky-client/pull/5 for more details.

**Comment by cyrezdev** [comment]
@ImLunaHey How do you want it to be set?

As for en, there are en-US, en-GB, en-CA... as well.
So, is it `"fr-fr": fr_fr` and file name fr-fr.ts ?

**Comment by ImLunaHey** [comment]
we'll move the english one to `en-AU` and then add in the others.

> So, is it "fr-fr": fr_fr and file name fr-fr.ts ?
that looks correct.

**Comment by cyrezdev** [comment]
PR updated

**Pull request merged**
